LegalAndGeneralConsultantCRM/Models/LeadFollowUp/FollowUp.cs
 using LegalAndGeneralConsultantCRM.Areas.Identity.Data;
using LegalAndGeneralConsultantCRM.Models.Leads;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LegalAndGeneralConsultantCRM.Models.LeadFollowUp
{
    public class FollowUp
    {

        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int FollowUpId { get; set; }
        public string? EmployeeId { get; set; }
        public LegalAndGeneralConsultantCRMUser Employee { get; set; }

        public int? LeadId { get; set; }
        public Lead Lead { get; set; }
        public DateTime? FollowUpDate { get; set; }
        public string? Status { get; set; }
        public DateTime? Reminder { get; set; }
        public string? Description { get; set; }
        public bool FollowUpCompleted { get; set; }
		public string ThemeColor { get; set; }
		public string Priorty { get; set; }
		public DateTime? FollowUpReminder { get; set; }
 


    }
}

LegalAndGeneralConsultantCRM/Models/Leads/LeadHistory.cs
using LegalAndGeneralConsultantCRM.Areas.Identity.Data;
using System;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace LegalAndGeneralConsultantCRM.Models.Leads
{
    public class LeadHistory
    {
        [Key]
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int LeadHistoryId { get; set; }

        // Foreign key to Lead
        public int? LeadId { get; set; }
        [ForeignKey("LeadId")]
        public Lead Lead { get; set; }  // Ensure you have 'using LegalAndGeneralConsultantCRM.Models.Leads;' for Lead class

        // Foreign key to User (assuming LegalAndGeneralConsultantCRMUser)
        public string? UserId { get; set; }
        [ForeignKey("UserId")]
        public LegalAndGeneralConsultantCRMUser User { get; set; }

        public string? Status { get; set; }
        public DateTime? LeadFollowupDate { get; set; }
    }
}

LegalAndGeneralConsultantCRM/ViewModels/Leads/BulkUploadViewModel.cs
using Microsoft.AspNetCore.Http;

namespace LegalAndGeneralConsultantCRM.ViewModels.Leads
{
    public class BulkUploadViewModel
    {
        public IFormFile File { get; set; }
    }
}

LegalAndGeneralConsultantCRM/ViewModels/Leads/LeadHistoryViewModel.cs
namespace LegalAndGeneralConsultantCRM.ViewModels.Leads
{
	public class LeadHistoryViewModel
	{
		public int LeadHistoryId { get; set; }
		public int? LeadId { get; set; }
		public string UserName { get; set; }
		public string FullName { get; set; }
		public string PhoneNumber { get; set; }
		public string Email { get; set; }
		public string Status { get; set; }
		public DateTime? LeadFollowupDate { get; set; }
	}
}

LegalAndGeneralConsultantCRM/Areas/Admin/Controllers/FollowupController.cs
using LegalAndGeneralConsultantCRM.Areas.Identity.Data;
using LegalAndGeneralConsultantCRM.Models.LeadFollowUp;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;

namespace LegalAndGeneralConsultantCRM.Areas.Admin.Controllers
{

	[Area("Admin")]
    [Authorize(Roles = "Admin")]


    public class FollowupController : Controller
    {

        private readonly LegalAndGeneralConsultantCRMContext _context;

        private readonly UserManager<LegalAndGeneralConsultantCRMUser> _userManager; 

        public FollowupController(LegalAndGeneralConsultantCRMContext context, UserManager<LegalAndGeneralConsultantCRMUser> userManager)
        {
            _context = context;
            _userManager = userManager;
        }
        public async Task<IActionResult> Index()
        {
            var followup = await _context.FollowUps.ToListAsync();
            return View(followup);
        }
        public async Task<IActionResult> Create()
        {

            var users = await _userManager.GetUsersInRoleAsync("Employee");
            ViewBag.UserList = new SelectList(users, "Id", "FirstName");

            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(FollowUp model)
        {

            try
            { 
                _context.FollowUps.Add(model);
                await _context.SaveChangesAsync();


                return RedirectToAction("FollowUps", "Lead", new { area = "Admin" });

            }
            catch (Exception ex)
            {

                return View("Error");
            }
        }


        [HttpGet]
        public async Task<IActionResult> Edit(int id)
        {
            var followUp = await _context.FollowUps.FindAsync(id);
            if (followUp == null)
            {
                return NotFound();
            }

             return View(followUp);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, FollowUp followUp)
        {
            

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(followUp);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!FollowUpExists(followUp.FollowUpId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }

            return View(followUp);
        }
        private bool FollowUpExists(int id)
        {
            return _context.FollowUps.Any(e => e.FollowUpId == id);
        }
    }
}

LegalAndGeneralConsultantCRM/Areas/Employee/Controllers/MyLeadController.cs
using LegalAndGeneralConsultantCRM.Areas.Identity.Data;
using LegalAndGeneralConsultantCRM.Models;
using LegalAndGeneralConsultantCRM.Models.ActivitiesLog;
using LegalAndGeneralConsultantCRM.Models.CalendarEvents;
using LegalAndGeneralConsultantCRM.Models.LeadFollowUp;
using LegalAndGeneralConsultantCRM.Models.Leads;
using LegalAndGeneralConsultantCRM.ViewModels;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using OfficeOpenXml;
using System.IO;
using System.ComponentModel;
using LegalAndGeneralConsultantCRM.ViewModels.Leads;

namespace LegalAndGeneralConsultantCRM.Areas.Employee.Controllers
{

	[Area("Employee")]
    [Authorize(Roles = "Employee")]
    public class MyLeadController : Controller
    {

        private readonly LegalAndGeneralConsultantCRMContext _context;
        private readonly UserManager<LegalAndGeneralConsultantCRMUser> _userManager;
        private readonly IHttpContextAccessor _httpContextAccessor; // Add IHttpContextAccessor

        public MyLeadController(LegalAndGeneralConsultantCRMContext context, UserManager<LegalAndGeneralConsultantCRMUser> userManager, IHttpContextAccessor httpContextAccessor)
        {
            _context = context;
            _userManager = userManager;
            _httpContextAccessor = httpContextAccessor;
        }
		// Action method to show history for a given leadId
		public async Task<IActionResult> HistoryLead(int leadId)
		{
			// Fetching history data related to the leadId
			var historyData = await _context.LeadHistories
				.Where(h => h.LeadId == leadId)
				.Include(h => h.User) // Include User data if needed
				.Select(h => new LeadHistoryViewModel
				{
					LeadHistoryId = h.LeadHistoryId,
					FullName = h.Lead.FirstName,
					Email = h.Lead.Email,
					PhoneNumber = h.Lead.PhoneNumber,
					LeadId = h.LeadId,
					UserName = h.User != null ? h.User.UserName : "Unknown", // Adjust as per User property
					Status = h.Status,
					LeadFollowupDate = h.LeadFollowupDate
				})
				.ToListAsync();

			return View(historyData);
		}
		public IActionResult BulkUpload()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> UploadData(IFormFile file, List<MappingViewModel> mappings, string dropdownValue)
        {
            try
            {
                var user = await _userManager.GetUserAsync(User);
                var currentUser = user?.Id;

                if (string.IsNullOrEmpty(currentUser))
                {
                    return Json(new { data = new List<object>() });
                }

                ExcelPackage.LicenseContext = OfficeOpenXml.LicenseContext.NonCommercial;

                if (file == null || file.Length == 0)
                {
                    ViewBag.FileError = "Please select a file.";
                    return View("BulkUpload");
                }

                using (var stream = new MemoryStream())
                {
                    await file.CopyToAsync(stream);
                    stream.Position = 0;

                    using (var package = new ExcelPackage(stream))
                    {
                        var worksheet = package.Workbook.Worksheets.First();
                        var rowCount = worksheet.Dimension.Rows;

                        var leadsToSave = new List<Lead>();

                        for (int row = 2; row <= rowCount; row++)
                        {
                            var lead = new Lead { UserId = currentUser };

                            foreach (var mapping in mappings)
                            {
                                var columnIndex = worksheet.Cells["1:1"]
                                                    .First(cell => cell.Value.ToString().Equals(mapping.ExcelColumn))
                                                    .Start.Column;
                                var value = worksheet.Cells[row, columnIndex].Value?.ToString();

                                if (!string.IsNullOrEmpty(value))
                                {
                                    switch (mapping.DbColumn)
                                    {
                                        case "FirstName":
                                            lead.FirstName = value;
                                            break;
                                        case "LastName":
                                            lead.LastName = value;
                                            break;
                                        case "PhoneNumber":
                                            lead.PhoneNumber = value.Trim();
                                            break;
                                            // Add other cases as needed
                                    }
                                }
                            }

                            leadsToSave.Add(lead);

                            if (leadsToSave.Count >= 100)
                            {
                                _context.Leads.AddRange(leadsToSave);
                                await _context.SaveChangesAsync();
                                leadsToSave.Clear();
                                return RedirectToAction("Form", "Application", new { area = "Employee" });
                            }
                        }

                        if (leadsToSave.Any())
                        {
                            _context.Leads.AddRange(leadsToSave);
                            await _context.SaveChangesAsync();
                            return RedirectToAction("Form", "Application", new { area = "Employee" });
                        }

                        TempData["Success"] = "Lead data successfully uploaded.";
                        return RedirectToAction("Form", "Application", new { area = "Employee" });
                    }
                }
            }
            catch (Exception ex)
            {
                Console.WriteLine("Error occurred: " + ex.Message);
                ViewBag.ErrorMessage = "An error occurred while uploading data. Please try again.";
                return RedirectToAction("Form", "Application", new { area = "Employee" });
            }
        }

        // Helper method to get the column index based on header name
        private int GetColumnIndex(ExcelWorksheet worksheet, string columnName)
        {
            var colCount = worksheet.Dimension?.Columns ?? 0;
            for (int col = 1; col <= colCount; col++)
            {
                if (worksheet.Cells[1, col].Value?.ToString().Trim() == columnName)
                {
                    return col;
                }
            }
            return -1; // Column not found
        }

        // Helper method to set Lead property value based on column mapping

        public async Task<IActionResult> Index()
        {
             
            return View();
        }
		public async Task<IActionResult> LeadHistory()
		{
            var user = await _userManager.GetUserAsync(User);
            var currentUser = user.Id;

            if (currentUser == null)
            {
                return Json(new { data = new List<object>() });
            }
            var leads = await _context.Leads.Where(lead => lead.UserId == currentUser).ToListAsync();
			var selectList = leads.Select(l => new SelectListItem
			{
				Value = l.LeadId.ToString(),
				Text = l.FirstName + " " + l.LastName
			}).ToList();

			ViewBag.Lead = selectList;
			return View();
		}

		public async Task<JsonResult> GetLeadDetails(int leadId)
		{
			var leadHistoryData = await _context.LeadHistories
				.Include(lh => lh.Lead)
				.Include(lh => lh.User)
				.Where(lh => lh.LeadId == leadId)
				.Select(lh => new
				{
					LeadFullName = lh.Lead.FirstName + " " + lh.Lead.LastName,
					Email = lh.Lead.Email,
					PhoneNumber = lh.Lead.PhoneNumber,
					Status = lh.Status,
					SLeadFollowupDatetatus = lh.LeadFollowupDate,
					Username = lh.User.FirstName + " " + lh.User.LastName // Assuming UserName is what you want to return
				})
				.ToListAsync();

			return Json(new { data = leadHistoryData });
		}

		public async Task<IActionResult> InProcessLead()
        {

            return View();
        }
        public async Task<JsonResult> GetAllocatedLeadData()
        {
			var user = await _userManager.GetUserAsync(User);
			var currentUser = user.Id;

			if (currentUser == null)
            {
                return Json(new { data = new List<object>() });
            }

            var excludedStatuses = new List<string> { "Dead Lead", "Converted Lead" };

            var allocatedLeads = _context.Leads
                      .Where(lead => lead.UserId == currentUser)
                      
                      .ToList();


            var leadData = allocatedLeads.Select(l => new
            {
                l.LeadId,
                l.FirstName,
                l.LastName,
                FullName = $"{l.FirstName} {l.LastName}",
                l.PhoneNumber,
                l.Email,
                l.Gender,
                l.LeadSource,
                l.City,
                l.Notes,
                CreatedDate = l.CreatedDate?.Date,
                
            });

            return Json(new { data = leadData });
        }
        public async Task<IActionResult> Edit(int id)
        { 
            var referrals = await _context.Referrals.ToListAsync();

            ViewBag.Referral = new SelectList(referrals, "ReferralId", "Name");
            var leadViewModel = await _context.Leads.FindAsync(id);
            if (leadViewModel == null)
            {
                return NotFound();
            }
            return View(leadViewModel);
        }
        [HttpPost]
        public async Task<IActionResult> EditLeadForm(int? leadId, Lead vm)

LegalAndGeneralConsultantCRM/Areas/Employee/Views/MyLead/Country.cshtml
<!-- Content Wrapper. Contains page content -->
<div class="content-wrapper">
	<div class="content-wrapper-before"></div>
	<div class="container-full">

		<!-- Main content -->
		<section class="content">
		 

			<div class="row fx-element-overlay">
				<div class="col-12 col-lg-6 col-xl-4">
					<div class="box box-default">
						<div class="fx-card-item">
							<div class="fx-card-avatar fx-overlay-1">
								<img src="~/images/product/uk-flag-london-1024x683.jpg" alt="user">
								<div class="fx-overlay scrl-up">
									<ul class="fx-info">
										<li><a class="btn btn-outline image-popup-vertical-fit" href="~/images/product/uk-flag-london-1024x683.jpg"><i class="mdi mdi-magnify"></i></a></li>
										<li><a class="btn btn-outline" href="javascript:void(0);"><i class="mdi mdi-delete"></i></a></li>
										<li><a class="btn btn-outline" href="javascript:void(0);"><i class="mdi mdi-settings"></i></a></li>
									</ul>
								</div>
							</div>
							<div class="fx-card-content text-left mb-0">
								<div class="product-text">
									<h2 class="pro-price text-blue">9</h2>
									<h4 class="box-title mb-0">  UK</h4>
									<small class="text-muted db">New University & Program</small>

 								</div>
							</div>
						</div>
					</div>
					<!-- /.box -->
				</div>
				<div class="col-12 col-lg-6 col-xl-4">
					<div class="box box-default">
						<div class="fx-card-item">
							<div class="fx-card-avatar fx-overlay-1">
								<img src="~/images/product/germany-flag-std__88891.jpg" alt="user">
								<div class="fx-overlay scrl-up">
									<ul class="fx-info">
										<li><a class="btn btn-outline image-popup-vertical-fit" href="~/images/product/germany-flag-std__88891.jpg"><i class="mdi mdi-magnify"></i></a></li>
										<li><a class="btn btn-outline" href="javascript:void(0);"><i class="mdi mdi-delete"></i></a></li>
										<li><a class="btn btn-outline" href="javascript:void(0);"><i class="mdi mdi-settings"></i></a></li>
									</ul>
								</div>
							</div>
							<div class="fx-card-content text-left mb-0">
								<div class="product-text">
									<h2 class="pro-price text-blue">3</h2>

 									<h4 class="box-title mb-0">  Germany</h4>
									<small class="text-muted db">New University & Program</small>
								</div>
							</div>
						</div>
					</div>
					<!-- /.box -->
				</div>
				<div class="col-12 col-lg-6 col-xl-4">
					<div class="box box-default">
						<div class="fx-card-item">
							<div class="fx-card-avatar fx-overlay-1">
								<img src="~/images/product/Australian-flag.jpg" alt="user">
								<div class="fx-overlay scrl-up">
									<ul class="fx-info">
										<li><a class="btn btn-outline image-popup-vertical-fit" href="~/images/product/Australian-flag.jpg"><i class="mdi mdi-magnify"></i></a></li>
										<li><a class="btn btn-outline" href="javascript:void(0);"><i class="mdi mdi-delete"></i></a></li>
										<li><a class="btn btn-outline" href="javascript:void(0);"><i class="mdi mdi-settings"></i></a></li>
									</ul>
								</div>
							</div>
							<div class="fx-card-content text-left mb-0">
								<div class="product-text">
									<h2 class="pro-price text-blue">7</h2>
									<h4 class="box-title mb-0">  Australia</h4>
									<small class="text-muted db">New University & Program</small>
								</div>
							</div>
						</div>
					</div>
					<!-- /.box -->
				</div>
				 
				 

			</div>

		</section>
		<!-- /.content -->
	</div>
</div>
<!-- /.content-wrapper -->

LegalAndGeneralConsultantCRM/Areas/Employee/Views/MyLead/CreateFollowUp.cshtml
@model LegalAndGeneralConsultantCRM.Models.LeadFollowUp.FollowUp

<style>
    .border1 {
        border: 2px solid #605e5e4c;
        padding: 10px;
        border-radius: 6px;
        margin: 20px 0px;
    }

    legend {
        background-color: lightgray;
        width: auto;
        padding: 5px 10px;
        border-radius: 4px;
        margin-top: -30px;
        font-size: medium;
        margin-left: 5%;
        font-weight: bold;
        font-family: arial;
    }

    .wor {
        margin-top: 20px;
    }
</style>

<main id="main" class="main ">


    <section class="section" style="width: 100%;">
        <div class="row col-md-12" style="width: 100%;margin: auto;">
            <div class="col-md-8" style="margin: auto;">



                <div class="card" style="width: 100%">
                    <div class="card-body">

                       

                            <form class="row g-3 g-3 needs-validation" novalidate asp-controller="MyLead" asp-action="Create" method="post" asp-area="Employee">
                                <div class="col-md-12 border1">
                                    <legend>Lead Follow-Ups</legend>


                                    <div class="col-md-12">
                                        <label for="inputCity" class="form-label">Lead Name</label>
                                        <input type="text" class="form-control" value="@ViewBag.FirstName" readonly />
                                    <input type="hidden" asp-for="LeadId" value="@ViewBag.LeadId" />

                                    </div>
                                    <div class="col-md-12">
                                        <label for="inputCity" class="form-label">Status*</label>
                                        <select asp-for="Status" class="form-control">
                                            <option value="" disabled selected>--- Select Lead Status ---</option>
                                        <option>Future Lead</option>
                                        <option>Cold Lead</option>
                                        <option>Warm Lead</option>
                                        <option>Hot Lead</option>
                                        <option>Converted Lead</option>
                                        <option>Dead Lead</option>

                                        </select>
                                    </div>
                                    <div class="col-md-12">
                                    <label for="inputState" class="form-label">Description</label>
                                        <textarea asp-for="Description" class="form-control" style="height: 100px"  ></textarea>
                                        <div class="invalid-feedback">Please enter your Source Details.</div>
                                        <br>
                                    </div>
                                    <div class="row">
                                        <div class="col-md-6">
                                            <label for="FollowUpDate" class="form-label">Follow-Up-Date </label>
                                            <input asp-for="FollowUpDate" type="date" class="form-control" >
                                            <div class="invalid-feedback">Please enter your Company.</div>
                                        </div>

                                        <div class="col-md-6">
                                            <label for="Reminder" class="form-label">Next-Follow-Up-Reminder</label>
                                            <input asp-for="Reminder" type="date" class="form-control"  >
                                            <div class="invalid-feedback">Please enter your Company.</div>
                                        </div>
                                    </div>




                                    <div class="col-md-12">
                                        <div class="float-end">
                                            <button type="submit" class="btn btn-primary  float-right">FollowUp</button>
                                        </div>
                                    </div>
                                </div>
                            </form>
 
                    </div>
                </div>

            </div>
        </div>



    </section>
</main>

LegalAndGeneralConsultantCRM/Areas/Employee/Views/MyLead/Status.cshtml
<div class="content-wrapper">
    <div class="content-wrapper-before"></div>
    <div class="container-full">
        <section class="content">
            <div class="content-header">
                <div class="d-flex align-items-center">
                    <div class="w-p100 d-md-flex align-items-center justify-content-between">
                         
                        <div class="d-inline-block align-items-center">
                            <nav>
                                <ol class="breadcrumb">
                                    <!-- Breadcrumb navigation can be added here if needed -->
                                </ol>
                            </nav>
                        </div>
                    </div>
                </div>
            </div>
            <div class="row">
                <div class="col-12">
                    <div class="box">
                        <div class="box-header with-border">
                            <h3 class="box-title">Leads Status</h3>
                          @*   <h6 class="box-subtitle">Export data to Copy, CSV, Excel, PDF & Print</h6> *@

                            <div class="container mt-4">
                                <div class="row">
                                    <div class="col-md-6">
                                        <form id="simpleSearchForm" class="form-inline">
                                            <div class="form-group">
                                                <label for="searchSelect" class="sr-only">Search</label>
                                                <select id="searchSelect" class="form-control mr-2">
                                                    <option value="" disabled>Select Lead Status</option>
                                                    <option value="Hot Lead">Hot Lead</option>
                                                    <option value="Dead Lead">Dead Lead</option>
                                                    <option value="Future Lead">Future Lead</option>
                                                    <option value="Converted Lead">Converted Lead</option>
                                                    <option value="Warm Lead">Warm Lead</option>
                                                </select>
                                            </div>
                                        </form>
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="box-body">
                            <div class="table-responsive">
                                <table id="leadTable" class="table table-bordered table-hover display nowrap margin-top-10 w-p100">
                                    <thead>
                                        <tr>
                                            <th style="background-color: #4e0973; color: white;">Name</th>
                                            <th style="background-color: #4e0973; color: white;">Email</th>
                                            <th style="background-color: #4e0973; color: white;">Gender</th>
                                            <th style="background-color: #4e0973; color: white;">Phone Number</th>
                                            <th style="background-color: #4e0973; color: white;">Status</th>
                                        </tr>
                                    </thead>
                                    <tbody>
                                        <!-- Table body content will be filled by DataTables -->
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    </div>
</div>

@section Scripts {
    <script>
        $(document).ready(function () {
            var table = $('#leadTable').DataTable({
                
                "ajax": {
                    "url": '@Url.Action("LeadByStatus", "MyLead", new { area = "Employee" })',
                    "data": function (d) {
                        d.status = $('#searchSelect').val();
                    }  ,
                    "datatype": "json"
                },
                "columns": [
                    { "data": "fullName" },
                    { "data": "email" },
                    { "data": "gender" },
                    { "data": "phoneNumber" },
                   
                    {
                        "data": "status",

                        "autoWidth": true,
                        "render": function (data, type, row) {
                            if (data === "Converted Lead") {
                                return '<span class="badge badge-pill bg-success">Converted Lead</span>';
                            } else if (data === "Dead Lead") {
                                return '<span class="badge badge-pill bg-danger">Dead Lead</span>';
                            } else if (data === "Cold Lead") {
                                return '<span class="badge badge-pill bg-dark">Cold Lead</span>';
                            } else if (data === "Future Lead") {
                                return '<span class="badge badge-pill bg-secondary">Future Lead</span>';
                            } else if (data === "Hot Lead") {
                                return '<span class="badge badge-pill bg-primary">Hot Lead</span>';
                            } else if (data === "Warm Lead") {
                                return '<span class="badge badge-pill bg-info">Warm Lead</span>';
                            } else {
                                return '<span class="badge badge-pill bg-warning">Pending Lead</span>';
                            }
                        }
                    },
                ]
            });

            $('#searchSelect').change(function () {
                table.ajax.reload();
            });
        });
    </script>
}